// Seed data — realistic Indian internship market for PM Internship Scheme
import type {
  Company,
  Internship,
  User,
  Notification,
} from "./types";

// ─── Companies ────────────────────────────────────────────────────────
export const SEED_COMPANIES: Company[] = [
  {
    id: "co_tcs",
    name: "Tata Consultancy Services",
    email: "careers@tcs.com",
    logoUrl: "",
    industry: "IT Services",
    description:
      "TCS is an IT services, consulting and business solutions organization that has been partnering with the world's best businesses for over 50 years.",
    website: "https://tcs.com",
    location: "Mumbai, India",
    size: "enterprise",
    verified: true,
    approved: true,
    rating: 4.2,
  },
  {
    id: "co_infosys",
    name: "Infosys",
    email: "talent@infosys.com",
    logoUrl: "",
    industry: "IT Services",
    description:
      "Infosys is a global leader in next-generation digital services and consulting, enabling clients in 50+ countries to navigate their digital transformation.",
    website: "https://infosys.com",
    location: "Bengaluru, India",
    size: "enterprise",
    verified: true,
    approved: true,
    rating: 4.1,
  },
  {
    id: "co_flipkart",
    name: "Flipkart",
    email: "interns@flipkart.com",
    logoUrl: "",
    industry: "E-commerce",
    description:
      "Flipkart is India's leading e-commerce marketplace with a registered customer base of over 450 million.",
    website: "https://flipkart.com",
    location: "Bengaluru, India",
    size: "large",
    verified: true,
    approved: true,
    rating: 4.3,
  },
  {
    id: "co_zoho",
    name: "Zoho Corporation",
    email: "careers@zoho.com",
    logoUrl: "",
    industry: "SaaS",
    description:
      "Zoho offers beautifully smart software to grow your business. From CRM to marketing automation, we build software that works the way you work.",
    website: "https://zoho.com",
    location: "Chennai, India",
    size: "large",
    verified: true,
    approved: true,
    rating: 4.4,
  },
  {
    id: "co_razorpay",
    name: "Razorpay",
    email: "talent@razorpay.com",
    logoUrl: "",
    industry: "Fintech",
    description:
      "Razorpay is the only payments solution in India that allows businesses to accept, process and disburse payments with its product suite.",
    website: "https://razorpay.com",
    location: "Bengaluru, India",
    size: "medium",
    verified: true,
    approved: true,
    rating: 4.5,
  },
  {
    id: "co_swiggy",
    name: "Swiggy",
    email: "careers@swiggy.com",
    logoUrl: "",
    industry: "Food Tech",
    description:
      "Swiggy is India's leading on-demand food delivery platform, connecting millions of customers with restaurants across 500+ cities.",
    website: "https://swiggy.com",
    location: "Bengaluru, India",
    size: "large",
    verified: true,
    approved: true,
    rating: 4.2,
  },
  {
    id: "co_zomato",
    name: "Zomato",
    email: "talent@zomato.com",
    logoUrl: "",
    industry: "Food Tech",
    description:
      "Zomato's mission is to ensure nobody has a bad meal. We connect customers, restaurant partners and delivery partners.",
    website: "https://zomato.com",
    location: "Gurugram, India",
    size: "large",
    verified: true,
    approved: true,
    rating: 4.1,
  },
  {
    id: "co_byjus",
    name: "BYJU'S",
    email: "careers@byjus.com",
    logoUrl: "",
    industry: "EdTech",
    description:
      "BYJU'S is the world's most valuable ed-tech company, creating highly adaptive, engaging and effective learning programs.",
    website: "https://byjus.com",
    location: "Bengaluru, India",
    size: "large",
    verified: true,
    approved: true,
    rating: 3.8,
  },
  {
    id: "co_paytm",
    name: "Paytm",
    email: "talent@paytm.com",
    logoUrl: "",
    industry: "Fintech",
    description:
      "Paytm is India's largest digital payment and financial services platform, offering payments, banking, lending and investment services.",
    website: "https://paytm.com",
    location: "Noida, India",
    size: "large",
    verified: true,
    approved: true,
    rating: 4.0,
  },
  {
    id: "co_freshworks",
    name: "Freshworks",
    email: "careers@freshworks.com",
    logoUrl: "",
    industry: "SaaS",
    description:
      "Freshworks makes it easy for businesses to delight their customers with AI-boosted software for customer service, IT, CRM and HR.",
    website: "https://freshworks.com",
    location: "Chennai, India",
    size: "medium",
    verified: true,
    approved: true,
    rating: 4.3,
  },
  {
    id: "co_phonepe",
    name: "PhonePe",
    email: "talent@phonepe.com",
    logoUrl: "",
    industry: "Fintech",
    description:
      "PhonePe is India's leading digital payments platform with over 400 million registered users.",
    website: "https://phonepe.com",
    location: "Bengaluru, India",
    size: "large",
    verified: true,
    approved: true,
    rating: 4.4,
  },
  {
    id: "co_cred",
    name: "CRED",
    email: "talent@cred.club",
    logoUrl: "",
    industry: "Fintech",
    description:
      "CRED is a members-only club that rewards individuals for timely credit card bill payments.",
    website: "https://cred.club",
    location: "Bengaluru, India",
    size: "medium",
    verified: true,
    approved: true,
    rating: 4.5,
  },
];

// ─── Internships ──────────────────────────────────────────────────────
export const SEED_INTERNSHIPS: Internship[] = [
  {
    id: "in_001",
    title: "Data Science Intern",
    companyId: "co_flipkart",
    description:
      "Join our data science team to build ML models that power personalized shopping experiences for 450M+ customers. You will work on recommendation systems, demand forecasting, and customer segmentation.",
    responsibilities: [
      "Build and deploy ML models for product recommendations",
      "Analyze large-scale customer behavior datasets",
      "Develop NLP pipelines for review sentiment analysis",
      "Collaborate with product teams on data-driven features",
      "Present findings to stakeholders weekly",
    ],
    requirements: [
      "Pursuing B.Tech/M.Tech in CS, EE, Statistics or related field",
      "Strong foundation in Python and SQL",
      "Familiarity with Pandas, NumPy, Scikit-learn",
      "Excellent problem-solving and communication skills",
    ],
    benefits: [
      "₹35,000/month stipend",
      "Mentorship from senior data scientists",
      "Free meals and transport",
      "Pre-placement offer opportunity",
      "Hands-on experience with petabyte-scale data",
    ],
    skills: ["Python", "SQL", "Machine Learning", "Pandas", "NumPy", "Scikit-learn", "Data Analysis"],
    domain: "Data Science",
    location: "Bengaluru, India",
    workMode: "onsite",
    duration: 12,
    stipend: 35000,
    openings: 5,
    deadline: "2026-08-30",
    isActive: true,
    createdAt: "2026-07-10T10:00:00Z",
  },
  {
    id: "in_002",
    title: "Full Stack Developer Intern",
    companyId: "co_razorpay",
    description:
      "Build the future of digital payments in India. You'll work on production-grade features used by millions of merchants, using React, Node.js and a microservices architecture.",
    responsibilities: [
      "Develop new features for the merchant dashboard",
      "Build RESTful APIs in Node.js with TypeScript",
      "Optimize database queries in PostgreSQL",
      "Write unit and integration tests",
      "Participate in code reviews and design discussions",
    ],
    requirements: [
      "Strong JavaScript/TypeScript skills",
      "Experience with React and Node.js",
      "Understanding of REST APIs and databases",
      "Familiarity with Git workflows",
    ],
    benefits: [
      "₹40,000/month stipend",
      "Stock options for top performers",
      "Modern tech stack",
      "Hackathon participation",
      "PPO opportunity",
    ],
    skills: ["React", "Node.js", "JavaScript", "TypeScript", "PostgreSQL", "REST", "MongoDB"],
    domain: "Web Development",
    location: "Bengaluru, India",
    workMode: "hybrid",
    duration: 16,
    stipend: 40000,
    openings: 3,
    deadline: "2026-08-15",
    isActive: true,
    createdAt: "2026-07-08T09:00:00Z",
  },
  {
    id: "in_003",
    title: "AI/ML Research Intern",
    companyId: "co_tcs",
    description:
      "Work on cutting-edge research in NLP, computer vision, and large language models at TCS Research. Co-author papers and contribute to enterprise-grade AI solutions.",
    responsibilities: [
      "Conduct literature surveys on LLM and NLP research",
      "Prototype and benchmark ML models",
      "Document experiments and write technical reports",
      "Collaborate with PhD researchers and senior scientists",
    ],
    requirements: [
      "B.Tech/M.Tech in CS, AI, or related field",
      "Strong Python and ML fundamentals",
      "Experience with PyTorch or TensorFlow",
      "Published research is a plus",
    ],
    benefits: [
      "₹30,000/month stipend",
      "Co-authorship on research papers",
      "Access to GPU clusters",
      "Conference travel support",
    ],
    skills: ["Python", "PyTorch", "TensorFlow", "NLP", "Deep Learning", "Machine Learning", "Computer Vision"],
    domain: "Artificial Intelligence",
    location: "Hyderabad, India",
    workMode: "onsite",
    duration: 24,
    stipend: 30000,
    openings: 4,
    deadline: "2026-09-01",
    isActive: true,
    createdAt: "2026-07-05T11:00:00Z",
  },
  {
    id: "in_004",
    title: "Frontend Engineer Intern",
    companyId: "co_zoho",
    description:
      "Build delightful UI for Zoho's suite of business applications used by 75M+ users worldwide. Work with React, TypeScript, and our in-house design system.",
    responsibilities: [
      "Build pixel-perfect, responsive UI components",
      "Collaborate with designers on design system evolution",
      "Optimize performance and accessibility",
      "Write clean, tested, documented code",
    ],
    requirements: [
      "Strong HTML, CSS, JavaScript skills",
      "Experience with React or Vue",
      "Eye for detail and design",
      "Knowledge of accessibility best practices",
    ],
    benefits: [
      "₹25,000/month stipend",
      "Free accommodation for outstation interns",
      "Mentorship program",
      "PPO opportunity",
    ],
    skills: ["React", "JavaScript", "TypeScript", "HTML", "CSS", "Tailwind", "Figma"],
    domain: "Web Development",
    location: "Chennai, India",
    workMode: "onsite",
    duration: 12,
    stipend: 25000,
    openings: 6,
    deadline: "2026-08-20",
    isActive: true,
    createdAt: "2026-07-12T08:30:00Z",
  },
  {
    id: "in_005",
    title: "Cloud DevOps Engineer Intern",
    companyId: "co_infosys",
    description:
      "Help enterprise clients migrate and operate workloads on AWS and Azure. You'll gain hands-on experience with Kubernetes, Terraform, and CI/CD pipelines.",
    responsibilities: [
      "Build and maintain CI/CD pipelines",
      "Provision infrastructure using Terraform",
      "Monitor and troubleshoot production systems",
      "Automate deployment processes",
    ],
    requirements: [
      "Understanding of Linux and networking",
      "Familiarity with AWS or Azure",
      "Scripting skills (Bash, Python)",
      "Willingness to learn DevOps tools",
    ],
    benefits: [
      "₹28,000/month stipend",
      "AWS certification sponsorship",
      "Enterprise-scale exposure",
      "PPO opportunity",
    ],
    skills: ["AWS", "Docker", "Kubernetes", "Linux", "Terraform", "CI/CD", "Python"],
    domain: "DevOps",
    location: "Pune, India",
    workMode: "hybrid",
    duration: 16,
    stipend: 28000,
    openings: 8,
    deadline: "2026-08-25",
    isActive: true,
    createdAt: "2026-07-09T14:00:00Z",
  },
  {
    id: "in_006",
    title: "UI/UX Design Intern",
    companyId: "co_freshworks",
    description:
      "Design beautiful, user-friendly experiences for Freshworks products. Conduct user research, create wireframes, and ship polished designs in Figma.",
    responsibilities: [
      "Conduct user research and usability testing",
      "Create wireframes, prototypes, and high-fidelity designs",
      "Collaborate with PMs and engineers on implementation",
      "Maintain and evolve the design system",
    ],
    requirements: [
      "Portfolio showcasing design work",
      "Proficiency in Figma",
      "Understanding of UX principles",
      "Strong communication skills",
    ],
    benefits: [
      "₹22,000/month stipend",
      "Design conference sponsorship",
      "Mentorship from senior designers",
      "Real product launches",
    ],
    skills: ["Figma", "UI/UX", "Wireframing", "Prototyping", "Photoshop", "Communication"],
    domain: "Design",
    location: "Chennai, India",
    workMode: "hybrid",
    duration: 12,
    stipend: 22000,
    openings: 3,
    deadline: "2026-08-18",
    isActive: true,
    createdAt: "2026-07-11T10:30:00Z",
  },
  {
    id: "in_007",
    title: "Backend Engineer Intern",
    companyId: "co_swiggy",
    description:
      "Scale Swiggy's order management and delivery allocation systems that handle millions of orders daily. Work with Go, Java, and high-throughput microservices.",
    responsibilities: [
      "Design and build scalable backend services",
      "Optimize database performance",
      "Implement caching and queueing strategies",
      "Write comprehensive tests",
    ],
    requirements: [
      "Strong programming fundamentals",
      "Experience with Go, Java, or Node.js",
      "Understanding of distributed systems",
      "Database knowledge (SQL/NoSQL)",
    ],
    benefits: [
      "₹35,000/month stipend",
      "Free meals and snacks",
      "High-traffic system exposure",
      "PPO opportunity",
    ],
    skills: ["Go", "Java", "Node.js", "PostgreSQL", "Redis", "Microservices", "REST"],
    domain: "Backend Development",
    location: "Bengaluru, India",
    workMode: "onsite",
    duration: 16,
    stipend: 35000,
    openings: 4,
    deadline: "2026-08-22",
    isActive: true,
    createdAt: "2026-07-07T12:00:00Z",
  },
  {
    id: "in_008",
    title: "Digital Marketing Intern",
    companyId: "co_zomato",
    description:
      "Drive growth through creative marketing campaigns for Zomato. Manage social media, run paid campaigns, and analyze performance data.",
    responsibilities: [
      "Create and schedule social media content",
      "Run Google and Facebook ad campaigns",
      "Analyze campaign performance and A/B test",
      "Collaborate with content and design teams",
    ],
    requirements: [
      "Passion for digital marketing",
      "Strong written communication",
      "Basic knowledge of analytics tools",
      "Creative thinking",
    ],
    benefits: [
      "₹18,000/month stipend",
      "Real campaign ownership",
      "Brand collaboration exposure",
      "PPO opportunity",
    ],
    skills: ["SEO", "Google Ads", "Content Marketing", "Social Media", "Analytics", "Copywriting"],
    domain: "Marketing",
    location: "Gurugram, India",
    workMode: "hybrid",
    duration: 12,
    stipend: 18000,
    openings: 5,
    deadline: "2026-08-28",
    isActive: true,
    createdAt: "2026-07-13T09:30:00Z",
  },
  {
    id: "in_009",
    title: "Data Analyst Intern",
    companyId: "co_paytm",
    description:
      "Turn raw data into actionable insights for Paytm's product and business teams. Build dashboards in Power BI and Tableau, and run deep-dive analyses.",
    responsibilities: [
      "Build and maintain dashboards in Power BI",
      "Write SQL queries for ad-hoc analysis",
      "Communicate insights to non-technical stakeholders",
      "Identify trends and opportunities",
    ],
    requirements: [
      "Strong SQL skills",
      "Experience with Excel and Power BI / Tableau",
      "Basic Python for data manipulation",
      "Storytelling with data",
    ],
    benefits: [
      "₹24,000/month stipend",
      "Fintech domain exposure",
      "Mentorship from senior analysts",
      "PPO opportunity",
    ],
    skills: ["SQL", "Power BI", "Tableau", "Excel", "Python", "Data Analysis", "Data Visualization"],
    domain: "Data Analytics",
    location: "Noida, India",
    workMode: "onsite",
    duration: 12,
    stipend: 24000,
    openings: 6,
    deadline: "2026-08-19",
    isActive: true,
    createdAt: "2026-07-06T11:00:00Z",
  },
  {
    id: "in_010",
    title: "Mobile App Developer Intern (Android)",
    companyId: "co_phonepe",
    description:
      "Build the next generation of PhonePe's Android app used by 400M+ users. Work with Kotlin, Jetpack Compose, and modern Android architecture.",
    responsibilities: [
      "Develop new features in Kotlin",
      "Work with Jetpack Compose for UI",
      "Optimize app performance and size",
      "Write unit and UI tests",
    ],
    requirements: [
      "Strong Kotlin or Java skills",
      "Understanding of Android architecture components",
      "Familiarity with REST APIs",
      "Knowledge of Material Design",
    ],
    benefits: [
      "₹30,000/month stipend",
      "Work on app with 400M+ users",
      "Modern Android stack",
      "PPO opportunity",
    ],
    skills: ["Kotlin", "Java", "Android", "REST", "UI/UX", "Git"],
    domain: "Mobile Development",
    location: "Bengaluru, India",
    workMode: "hybrid",
    duration: 16,
    stipend: 30000,
    openings: 4,
    deadline: "2026-08-21",
    isActive: true,
    createdAt: "2026-07-04T13:00:00Z",
  },
  {
    id: "in_011",
    title: "Product Management Intern",
    companyId: "co_cred",
    description:
      "Drive product strategy and execution at CRED. Work with designers, engineers, and data scientists to ship features that delight members.",
    responsibilities: [
      "Conduct user research and competitive analysis",
      "Define product requirements and roadmaps",
      "Collaborate with cross-functional teams",
      "Analyze metrics and iterate on features",
    ],
    requirements: [
      "Strong analytical and communication skills",
      "Understanding of product metrics",
      "Prior PM or startup experience preferred",
      "Bias for action",
    ],
    benefits: [
      "₹45,000/month stipend",
      "Direct exposure to founders",
      "Stock options for top performers",
      "Real product ownership",
    ],
    skills: ["Communication", "Analytics", "Project Management", "Problem Solving", "SQL", "Presentation"],
    domain: "Product Management",
    location: "Bengaluru, India",
    workMode: "onsite",
    duration: 12,
    stipend: 45000,
    openings: 2,
    deadline: "2026-08-10",
    isActive: true,
    createdAt: "2026-07-14T10:00:00Z",
  },
  {
    id: "in_012",
    title: "Cybersecurity Intern",
    companyId: "co_tcs",
    description:
      "Join TCS's cybersecurity practice. Help enterprises detect, prevent, and respond to security threats. Work with SIEM, threat intel, and red team tools.",
    responsibilities: [
      "Monitor and analyze security events",
      "Perform vulnerability assessments",
      "Develop threat detection rules",
      "Document incidents and remediations",
    ],
    requirements: [
      "Understanding of network security fundamentals",
      "Familiarity with Linux and scripting",
      "Knowledge of OWASP Top 10",
      "Security certifications (a plus)",
    ],
    benefits: [
      "₹26,000/month stipend",
      "Industry certifications sponsorship",
      "Enterprise client exposure",
      "PPO opportunity",
    ],
    skills: ["Linux", "Python", "Bash", "Networking", "AWS", "Problem Solving"],
    domain: "Cybersecurity",
    location: "Hyderabad, India",
    workMode: "remote",
    duration: 12,
    stipend: 26000,
    openings: 5,
    deadline: "2026-09-05",
    isActive: true,
    createdAt: "2026-07-03T08:00:00Z",
  },
];

// ─── Sample student ───────────────────────────────────────────────────
export const SEED_STUDENT: User = {
  id: "u_demo_student",
  email: "arjun.sharma@student.edu",
  name: "Arjun Sharma",
  role: "STUDENT",
  phone: "+91 98765 43210",
  college: "Indian Institute of Technology, Madras",
  degree: "B.Tech",
  branch: "Computer Science Engineering",
  cgpa: 8.7,
  graduationYear: 2027,
  skills: ["Python", "JavaScript", "React", "Node.js", "SQL", "Machine Learning", "Pandas", "NumPy"],
  interests: ["Data Science", "Web Development", "Artificial Intelligence"],
  preferredLocations: ["Bengaluru", "Remote", "Hyderabad"],
  languages: ["English", "Hindi", "Telugu"],
  linkedin: "https://linkedin.com/in/arjun-sharma",
  github: "https://github.com/arjun-sharma",
  portfolio: "https://arjun.dev",
  extractedSkills: ["Python", "JavaScript", "React", "Node.js", "SQL", "Machine Learning", "Pandas", "NumPy"],
  profileCompleted: 85,
  isVerified: true,
  isApproved: true,
  emailVerified: true,
};

export const SEED_COMPANY_USER: User = {
  id: "u_demo_company",
  email: "hr@flipkart.com",
  name: "Priya Reddy",
  role: "COMPANY",
  companyId: "co_flipkart",
  profileCompleted: 100,
  isVerified: true,
  isApproved: true,
  emailVerified: true,
  skills: [],
  interests: [],
  preferredLocations: [],
  languages: [],
  extractedSkills: [],
};

export const SEED_ADMIN_USER: User = {
  id: "u_demo_admin",
  email: "admin@pm-internship.gov.in",
  name: "System Administrator",
  role: "ADMIN",
  profileCompleted: 100,
  isVerified: true,
  isApproved: true,
  emailVerified: true,
  skills: [],
  interests: [],
  preferredLocations: [],
  languages: [],
  extractedSkills: [],
};

export const SEED_NOTIFICATIONS: Notification[] = [
  {
    id: "n_001",
    userId: "u_demo_student",
    title: "New internship match!",
    message: "Data Science Intern at Flipkart — 92% match with your profile.",
    type: "INFO",
    read: false,
    createdAt: "2026-07-21T10:00:00Z",
  },
  {
    id: "n_002",
    userId: "u_demo_student",
    title: "Application under review",
    message: "Your application for AI/ML Research Intern at TCS is now under review.",
    type: "APPLICATION",
    read: false,
    createdAt: "2026-07-20T15:30:00Z",
  },
  {
    id: "n_003",
    userId: "u_demo_student",
    title: "Interview scheduled",
    message: "Your interview for Full Stack Developer Intern at Razorpay is scheduled for July 25.",
    type: "INTERVIEW",
    read: true,
    createdAt: "2026-07-18T09:15:00Z",
  },
  {
    id: "n_004",
    userId: "u_demo_student",
    title: "Profile 85% complete",
    message: "Add your GitHub projects to boost your profile to 100%.",
    type: "WARNING",
    read: true,
    createdAt: "2026-07-17T11:45:00Z",
  },
];

// ─── Landing page testimonials ────────────────────────────────────────
export const TESTIMONIALS = [
  {
    name: "Sneha Patel",
    role: "Data Science Intern at Flipkart",
    image: "",
    quote:
      "The AI recommendation engine matched me with 12 internships in my dream domain. Got an offer from Flipkart within 2 weeks of applying!",
    rating: 5,
  },
  {
    name: "Rohit Kumar",
    role: "Full Stack Intern at Razorpay",
    image: "",
    quote:
      "The skill gap analysis was a game-changer. I learned exactly what I needed to crack interviews at top companies.",
    rating: 5,
  },
  {
    name: "Ananya Iyer",
    role: "UI/UX Intern at Freshworks",
    image: "",
    quote:
      "The chatbot guided me through every step — from resume building to interview tips. Felt like having a personal career coach.",
    rating: 5,
  },
  {
    name: "Vikram Singh",
    role: "DevOps Intern at Infosys",
    image: "",
    quote:
      "The match percentage feature gave me confidence to apply. The application tracking kept me informed throughout.",
    rating: 5,
  },
  {
    name: "Pooja Nair",
    role: "ML Research Intern at TCS",
    image: "",
    quote:
      "The resume parser automatically extracted all my skills. Saved hours of manual entry. Brilliant platform!",
    rating: 5,
  },
  {
    name: "Karthik Reddy",
    role: "Product Intern at CRED",
    image: "",
    quote:
      "From application to certificate, the entire journey was seamless. Got my completion certificate in 12 weeks.",
    rating: 5,
  },
];

export const FAQS = [
  {
    q: "What is the PM Internship Scheme?",
    a: "The PM Internship Scheme is a Government of India initiative that provides internship opportunities to youth across India, connecting them with top companies for hands-on industry experience and skill development.",
  },
  {
    q: "How does the AI recommendation engine work?",
    a: "Our hybrid engine combines content-based filtering (skill cosine similarity), collaborative filtering (Jaccard overlap), location and domain preferences, and stipend/duration heuristics to compute a 0-100 match score for every internship. Every score is explainable — you can see exactly why an internship matched.",
  },
  {
    q: "Can I apply for internships without uploading a resume?",
    a: "Yes, but we strongly recommend uploading your resume. Our AI parser automatically extracts your skills, education, projects, and experience — boosting your match accuracy and saving you 30+ minutes of manual data entry.",
  },
  {
    q: "Is the platform free for students?",
    a: "Yes, the platform is completely free for students under the PM Internship Scheme. Companies pay a nominal listing fee, and the government subsidizes participation for eligible candidates.",
  },
  {
    q: "How long are the internships?",
    a: "Internships range from 8 to 24 weeks. Most are 12-16 weeks. You can filter by duration in the search page to find internships that fit your academic calendar.",
  },
  {
    q: "Will I get a certificate after completion?",
    a: "Yes, every completed internship comes with a verified digital certificate that includes your name, the internship title, the company, and the skills you demonstrated. Certificates are verifiable via a unique ID.",
  },
  {
    q: "Can companies hire interns full-time after the internship?",
    a: "Yes, many companies offer Pre-Placement Offers (PPOs) to top-performing interns. Each internship listing indicates whether PPO is offered.",
  },
  {
    q: "Does the platform support mobile devices?",
    a: "Yes, the platform is a Progressive Web App (PWA) — installable on Android and iOS, works offline for previously loaded data, and provides a native-app-like experience with bottom navigation and touch gestures.",
  },
];

export const STATS = [
  { label: "Active Students", value: "1,250,000+", icon: "users" },
  { label: "Partner Companies", value: "12,500+", icon: "building" },
  { label: "Open Internships", value: "45,000+", icon: "briefcase" },
  { label: "Successful Placements", value: "320,000+", icon: "check-circle" },
];
